import { z } from "zod";
const httpsUrl = z.string().url().refine((value) => new URL(value).protocol === "https:");
const text = z.string().max(12000);
const section = z.object({ heading: text, paragraphs: z.array(text).max(30), bullets: z.array(text).max(30).optional(), diagram: z.enum(["state-boundary","pd-critical-path","direct-linker"]).optional(), code: text.optional(), diagramUrl: httpsUrl.optional(), diagramDownloadUrl: httpsUrl.optional(), diagramCaption: text.optional() });
const post = z.object({ slug:z.string().regex(/^[a-z0-9-]{1,100}$/), title:text, subtitle:text, date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/), category:text,tags:z.array(text).max(20),kind:text,summary:text,outline:z.array(text).min(1).max(16),sections:z.array(section).min(1).max(16),takeaways:z.array(text).max(20),openQuestions:z.array(text).max(20),relatedSlugs:z.array(z.string().regex(/^[a-z0-9-]+$/)).max(20),sources:z.array(z.object({title:text,url:httpsUrl})).max(40),disclosure:text });
const dailyItem=z.object({id:text,rank:text,category:text,title:text,summary:text,why:text,source:httpsUrl,sourceLabel:text,reading:text,signal:z.enum(["high","medium"]),columns:z.array(text)});
const daily=z.object({year:z.number().int(),issueMeta:z.record(z.object({headline:text,subtitle:text,threadTitle:text,threadSummary:text})).optional(),reports:z.record(z.array(dailyItem)),dates:z.array(z.object({day:text,week:text,key:text})),columns:z.array(z.object({id:text,name:text,code:text,description:text,color:text})),topicBars:z.array(z.object({label:text,value:z.number(),color:text}))});
const experiment=z.object({id:text,title:text,hypothesis:text,method:z.array(text),metrics:z.array(text),falsifier:text,related:z.array(z.string().regex(/^[a-z0-9-]+$/))});
export const blogSchema = z.object({schemaVersion:z.literal(1),updatedAt:z.string(),posts:z.array(post).min(1).max(1000),daily:daily.optional(),experiments:z.array(experiment).optional()}).superRefine((value,ctx)=>{if(new Set(value.posts.map(p=>p.slug)).size!==value.posts.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:"Duplicate article slug"});for(const p of value.posts){if(p.outline.length!==p.sections.length)ctx.addIssue({code:z.ZodIssueCode.custom,message:`Outline mismatch: ${p.slug}`});}});
